platform :ios, '16.0'
use_frameworks!

target 'HMUApp' do
  # OAuth2/OpenID Connect for Keycloak SSO
  pod 'AppAuth', '~> 1.7'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['SWIFT_VERSION'] = '5.9'
    end
  end
end
